services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./config/server.properties:/data/server.properties
      - ./config/mods:/data/mods
      - ./config/config/:/data/config/
      - ./config/world:/data/world
